project_id = "eyevvanvdvcxdqyxzwfr"

[functions.facebook-ads]
verify_jwt = false

[functions.shopify-data]
verify_jwt = false

[functions.sales-analysis]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.hoko-api]
verify_jwt = false
