project_id = "eyevvanvdvcxdqyxzwfr"

[functions.facebook-ads]
verify_jwt = true

[functions.facebook-oauth-start]
verify_jwt = true

[functions.facebook-oauth-callback]
verify_jwt = false

[functions.facebook-user-ads]
verify_jwt = true

[functions.shopify-data]
verify_jwt = true

[functions.sales-analysis]
verify_jwt = true

[functions.get-mapbox-token]
verify_jwt = true

[functions.hoko-api]
verify_jwt = true

[functions.visitor-count]
verify_jwt = false

[functions.google-analytics]
verify_jwt = true

[functions.vturb-analytics]
verify_jwt = true

[functions.ga4-realtime]
verify_jwt = true
